name: Generate pacman animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate pacman-contribution-graph.svg
        uses: ZephrFish/pacman-contribution-graph@6fa1ebcf76d799d3de525d3e0f86c8d7029ea002
        with:
          github_user_name: ${{ github.repository_owner }}
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
